### ISSUE TITLE
Some pseudo-localized strings with placeholder fail to format under IE

### ISSUE THREAD

**Issue by eugene-stepanov** [ppatotski/app-localizer#6]
We encountered an issue with some pseudo-localized strings in **IE** browser. E.g.
1. Original EN string was:

> Displaying {start, number} - {end, number} of {total, number} Results

2. Pseudo-localized PSEUDO string is:

> ÐÐîššþļååýîîñĝ {start, number, null} ‐ {end, number, null} ööƒ {total, number, null} ŔŔéššûļļţš

When the pseudo string is passed to **localize** function a JS exception occurs deep inside **intl-messageformat** library: **"RangeError: Locale 'pseudo' is not well-formed**

PS: It still works fine in **Chrome** browser though.

**Comment by ppatotski** [comment]
Thanks for reporting. It does not like style:null probably. Let me look into it.
